/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConferencesRouteImport } from './routes/conferences'
import { Route as IksDialogueRouteImport } from './routes/iks-dialogue'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ResearchAbstractsRouteImport } from './routes/research-abstracts'
import { Route as ResearchImpactRouteImport } from './routes/research-impact'
import { Route as ResearchOpportunitiesRouteImport } from './routes/research-opportunities'
import { Route as ResearchersRouteImport } from './routes/researchers'
import { Route as SubmitResearchRouteImport } from './routes/submit-research'
import { Route as WhitePapersRouteImport } from './routes/white-papers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const IksDialogueRoute = IksDialogueRouteImport.update({
  id: '/iks-dialogue',
  path: '/iks-dialogue',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchAbstractsRoute = ResearchAbstractsRouteImport.update({
  id: '/research-abstracts',
  path: '/research-abstracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchImpactRoute = ResearchImpactRouteImport.update({
  id: '/research-impact',
  path: '/research-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchOpportunitiesRoute = ResearchOpportunitiesRouteImport.update({
  id: '/research-opportunities',
  path: '/research-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchersRoute = ResearchersRouteImport.update({
  id: '/researchers',
  path: '/researchers',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitResearchRoute = SubmitResearchRouteImport.update({
  id: '/submit-research',
  path: '/submit-research',
  getParentRoute: () => rootRouteImport,
} as any)
const WhitePapersRoute = WhitePapersRouteImport.update({
  id: '/white-papers',
  path: '/white-papers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conferences': typeof ConferencesRoute
  '/iks-dialogue': typeof IksDialogueRoute
  '/institutions': typeof InstitutionsRoute
  '/membership': typeof MembershipRoute
  '/methodology': typeof MethodologyRoute
  '/research': typeof ResearchRoute
  '/research-abstracts': typeof ResearchAbstractsRoute
  '/research-impact': typeof ResearchImpactRoute
  '/research-opportunities': typeof ResearchOpportunitiesRoute
  '/researchers': typeof ResearchersRoute
  '/submit-research': typeof SubmitResearchRoute
  '/white-papers': typeof WhitePapersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conferences': typeof ConferencesRoute
  '/iks-dialogue': typeof IksDialogueRoute
  '/institutions': typeof InstitutionsRoute
  '/membership': typeof MembershipRoute
  '/methodology': typeof MethodologyRoute
  '/research': typeof ResearchRoute
  '/research-abstracts': typeof ResearchAbstractsRoute
  '/research-impact': typeof ResearchImpactRoute
  '/research-opportunities': typeof ResearchOpportunitiesRoute
  '/researchers': typeof ResearchersRoute
  '/submit-research': typeof SubmitResearchRoute
  '/white-papers': typeof WhitePapersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conferences': typeof ConferencesRoute
  '/iks-dialogue': typeof IksDialogueRoute
  '/institutions': typeof InstitutionsRoute
  '/membership': typeof MembershipRoute
  '/methodology': typeof MethodologyRoute
  '/research': typeof ResearchRoute
  '/research-abstracts': typeof ResearchAbstractsRoute
  '/research-impact': typeof ResearchImpactRoute
  '/research-opportunities': typeof ResearchOpportunitiesRoute
  '/researchers': typeof ResearchersRoute
  '/submit-research': typeof SubmitResearchRoute
  '/white-papers': typeof WhitePapersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/conferences'
    | '/iks-dialogue'
    | '/institutions'
    | '/membership'
    | '/methodology'
    | '/research'
    | '/research-abstracts'
    | '/research-impact'
    | '/research-opportunities'
    | '/researchers'
    | '/submit-research'
    | '/white-papers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/conferences'
    | '/iks-dialogue'
    | '/institutions'
    | '/membership'
    | '/methodology'
    | '/research'
    | '/research-abstracts'
    | '/research-impact'
    | '/research-opportunities'
    | '/researchers'
    | '/submit-research'
    | '/white-papers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/conferences'
    | '/iks-dialogue'
    | '/institutions'
    | '/membership'
    | '/methodology'
    | '/research'
    | '/research-abstracts'
    | '/research-impact'
    | '/research-opportunities'
    | '/researchers'
    | '/submit-research'
    | '/white-papers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConferencesRoute: typeof ConferencesRoute
  IksDialogueRoute: typeof IksDialogueRoute
  InstitutionsRoute: typeof InstitutionsRoute
  MembershipRoute: typeof MembershipRoute
  MethodologyRoute: typeof MethodologyRoute
  ResearchRoute: typeof ResearchRoute
  ResearchAbstractsRoute: typeof ResearchAbstractsRoute
  ResearchImpactRoute: typeof ResearchImpactRoute
  ResearchOpportunitiesRoute: typeof ResearchOpportunitiesRoute
  ResearchersRoute: typeof ResearchersRoute
  SubmitResearchRoute: typeof SubmitResearchRoute
  WhitePapersRoute: typeof WhitePapersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences': {
      id: '/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iks-dialogue': {
      id: '/iks-dialogue'
      path: '/iks-dialogue'
      fullPath: '/iks-dialogue'
      preLoaderRoute: typeof IksDialogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-abstracts': {
      id: '/research-abstracts'
      path: '/research-abstracts'
      fullPath: '/research-abstracts'
      preLoaderRoute: typeof ResearchAbstractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-impact': {
      id: '/research-impact'
      path: '/research-impact'
      fullPath: '/research-impact'
      preLoaderRoute: typeof ResearchImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-opportunities': {
      id: '/research-opportunities'
      path: '/research-opportunities'
      fullPath: '/research-opportunities'
      preLoaderRoute: typeof ResearchOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researchers': {
      id: '/researchers'
      path: '/researchers'
      fullPath: '/researchers'
      preLoaderRoute: typeof ResearchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-research': {
      id: '/submit-research'
      path: '/submit-research'
      fullPath: '/submit-research'
      preLoaderRoute: typeof SubmitResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/white-papers': {
      id: '/white-papers'
      path: '/white-papers'
      fullPath: '/white-papers'
      preLoaderRoute: typeof WhitePapersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConferencesRoute: ConferencesRoute,
  IksDialogueRoute: IksDialogueRoute,
  InstitutionsRoute: InstitutionsRoute,
  MembershipRoute: MembershipRoute,
  MethodologyRoute: MethodologyRoute,
  ResearchRoute: ResearchRoute,
  ResearchAbstractsRoute: ResearchAbstractsRoute,
  ResearchImpactRoute: ResearchImpactRoute,
  ResearchOpportunitiesRoute: ResearchOpportunitiesRoute,
  ResearchersRoute: ResearchersRoute,
  SubmitResearchRoute: SubmitResearchRoute,
  WhitePapersRoute: WhitePapersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
